export type QuestionnaireScale = {
  label: string;
  label_bn?: string;
  label_hi?: string;
  label_mr?: string;
  value: number;
};

export type QuestionnaireItem = {
  id: string;
  text: string;
  text_bn?: string;
  text_hi?: string;
  text_mr?: string;
  isReverse: boolean;
};

export type ScoringType = "sum" | "mean" | "tsis_subscales" | "dass21_subscales" | "none";
export type OrderType = "random" | "buildup" | "normal";

export type QuestionnaireDef = {
  id: string;
  title: string;
  title_bn?: string;
  title_hi?: string;
  title_mr?: string;
  description: string;
  description_bn?: string;
  description_hi?: string;
  description_mr?: string;
  scale: QuestionnaireScale[];
  items: QuestionnaireItem[];
  scoringType: ScoringType;
  orderType: OrderType;
  feedbackTemplate: string;
  scaleMin: number;
  scaleMax: number;
};

export const QUESTIONNAIRES: QuestionnaireDef[] = [
  {
    id: "cfs",
    title: "Cognitive Flexibility Scale (CFS)",
    title_bn: "কগনিটিভ ফ্লেক্সিবিলিটি স্কেল (CFS)",
    title_hi: "संज्ञानात्मक लचीलापन पैमाना (CFS)",
    title_mr: "संज्ञानात्मक लवचिकता प्रमाण (CFS)",
    description: "The following statements deal with your beliefs and feelings about your own behavior. Read each statement and respond by selecting how much you agree or disagree with each statement.",
    description_bn: "নিম্নলিখিত বিবৃতিগুলি আপনার নিজের আচরণ সম্পর্কে আপনার বিশ্বাস এবং অনুভূতির সাথে সম্পর্কিত। প্রতিটি বিবৃতি পড়ুন এবং আপনি প্রতিটি বিবৃতির সাথে কতটা একমত বা দ্বিমত পোষণ করেন তা নির্বাচন করে উত্তর দিন।",
    description_hi: "निम्नलिखित कथन आपके अपने व्यवहार के बारे में आपकी मान्यताओं और भावनाओं से संबंधित हैं। प्रत्येक कथन को पढ़ें और बताएं कि आप प्रत्येक कथन से कितना सहमत या असहमत हैं।",
    description_mr: "खालील विधाने तुमच्या स्वतःच्या वर्तनाबद्दलच्या तुमच्या समजुती आणि भावनांशी संबंधित आहेत. प्रत्येक विधान वाचा आणि आपण प्रत्येक विधानाशी किती सहमत किंवा असहमत आहात ते निवडून उत्तर द्या.",
    scaleMin: 1,
    scaleMax: 6,
    scale: [
      { label: "strongly agree", label_bn: "সম্পূর্ণ একমত", label_hi: "पूर्णतः सहमत", label_mr: "पूर्णपणे सहमत", value: 6 },
      { label: "agree", label_bn: "একমত", label_hi: "सहमत", label_mr: "सहमत", value: 5 },
      { label: "slightly agree", label_bn: "কিছুটা একমত", label_hi: "थोड़ा सहमत", label_mr: "काही प्रमाणात सहमत", value: 4 },
      { label: "slightly disagree", label_bn: "কিছুটা দ্বিমত", label_hi: "थोड़ा असहमत", label_mr: "काही प्रमाणात असहमत", value: 3 },
      { label: "disagree", label_bn: "দ্বিমত", label_hi: "असहमत", label_mr: "असहमत", value: 2 },
      { label: "strongly disagree", label_bn: "সম্পূর্ণ দ্বিমত", label_hi: "पूर्णतः असहमत", label_mr: "पूर्णपणे असहमत", value: 1 },
    ],
    orderType: "random",
    scoringType: "sum",
    feedbackTemplate: "Your feedback on the cognitive flexibility scale is {score}. The average score among students is (around) 55 points.",
    items: [
      { id: "q1", text: "I can communicate an idea in many different ways.", text_bn: "আমি বিভিন্ন উপায়ে একটি ধারণা প্রকাশ করতে পারি।", text_hi: "मैं किसी विचार को कई अलग-अलग तरीकों से व्यक्त कर सकता हूँ।", text_mr: "मी एखादी कल्पना अनेक वेगवेगळ्या प्रकारे व्यक्त करू शकतो/शकते.", isReverse: false },
      { id: "q2", text: "I avoid new and unusual situations.", text_bn: "আমি নতুন এবং অস্বাভাবিক পরিস্থিতি এড়িয়ে চলি।", text_hi: "मैं नई और असामान्य परिस्थितियों से बचता हूँ।", text_mr: "मी नवीन आणि असामान्य परिस्थिती टाळतो/टाळते.", isReverse: true },
      { id: "q3", text: "I feel like I never get to make decisions.", text_bn: "আমার মনে হয় আমি কখনোই সিদ্ধান্ত নেওয়ার সুযোগ পাই না।", text_hi: "मुझे ऐसा लगता है कि मुझे कभी निर्णय लेने का मौका नहीं मिलता।", text_mr: "मला असे वाटते की मला कधीही निर्णय घेण्याची संधी मिळत नाही.", isReverse: true },
      { id: "q4", text: "I can find workable solutions to seemingly unsolvable problems.", text_bn: "আমি আপাতদৃষ্টিতে অমীমাংসিত সমস্যার কার্যকর সমাধান খুঁজে পেতে পারি।", text_hi: "मैं असंभव दिखने वाली समस्याओं के व्यावहारिक समाधान खोज सकता हूँ।", text_mr: "मी वरवर न सुटणाऱ्या समस्यांवर व्यावहारिक उपाय शोधू शकतो/शकते.", isReverse: false },
      { id: "q5", text: "I seldom have choices when deciding how to behave.", text_bn: "কীভাবে আচরণ করতে হবে তার সিদ্ধান্ত নেওয়ার সময় আমার কাছে খুব কমই বিকল্প থাকে।", text_hi: "व्यवहार करने का निर्णय लेते समय मेरे पास शायद ही कभी विकल्प होते हैं।", text_mr: "कसे वागायचे हे ठरवताना माझ्याकडे क्वचितच पर्याय असतात.", isReverse: true },
      { id: "q6", text: "I am willing to work at creative solutions to problems.", text_bn: "আমি সমস্যার সৃজনশীল সমাধানে কাজ করতে ইচ্ছুক।", text_hi: "मैं समस्याओं के रचनात्मक समाधान खोजने के लिए काम करने को तैयार हूँ।", text_mr: "मी समस्यांवर सर्जनशील उपाय शोधण्यासाठी काम करण्यास तयार आहे.", isReverse: false },
      { id: "q7", text: "In any given situation, I am able to act appropriately.", text_bn: "যেকোনো নির্দিষ্ট পরিস্থিতিতে, আমি যথাযথভাবে কাজ করতে সক্ষম।", text_hi: "किसी भी परिस्थिति में, मैं उचित व्यवहार करने में सक्षम हूँ।", text_mr: "कोणत्याही दिलेल्या परिस्थितीत, मी योग्य वागण्यास सक्षम आहे.", isReverse: false },
      { id: "q8", text: "My behavior is a result of conscious decisions that I make.", text_bn: "আমার আচরণ আমার নেওয়া সচেতন সিদ্ধান্তের ফলাফল।", text_hi: "मेरा व्यवहार मेरे द्वारा लिए गए सचेत निर्णयों का परिणाम है।", text_mr: "माझे वर्तन हे मी घेतलेल्या जाणीवपूर्वक निर्णयांचा परिणाम आहे.", isReverse: false },
      { id: "q9", text: "I have many possible ways of behaving in any given situation.", text_bn: "যেকোনো নির্দিষ্ট পরিস্থিতিতে আমার আচরণের সম্ভাব্য অনেক উপায় আছে।", text_hi: "किसी भी परिस्थिति में मेरे पास व्यवहार करने के कई संभावित तरीके होते हैं।", text_mr: "कोणत्याही दिलेल्या परिस्थितीत माझ्याकडे वागण्याचे अनेक संभाव्य मार्ग असतात.", isReverse: false },
      { id: "q10", text: "I have difficulty using my knowledge on a given topic in real life situations.", text_bn: "বাস্তব জীবনের পরিস্থিতিতে কোনো নির্দিষ্ট বিষয়ে আমার জ্ঞান ব্যবহার করতে আমার অসুবিধা হয়।", text_hi: "मुझे वास्तविक जीवन की स्थितियों में किसी विषय पर अपने ज्ञान का उपयोग करने में कठिनाई होती है।", text_mr: "मला वास्तविक जीवनातील परिस्थितीत दिलेल्या विषयावर माझे ज्ञान वापरण्यात अडचण येते.", isReverse: true },
      { id: "q11", text: "I am willing to listen and consider alternatives for handling a problem.", text_bn: "আমি একটি সমস্যা মোকাবিলার বিকল্প উপায় শুনতে এবং বিবেচনা করতে ইচ্ছুক।", text_hi: "मैं किसी समस्या से निपटने के विकल्पों को सुनने और उन पर विचार करने को तैयार हूँ।", text_mr: "मी समस्येला सामोरे जाण्यासाठी पर्यायी मार्ग ऐकण्यास आणि विचार करण्यास तयार आहे.", isReverse: false },
      { id: "q12", text: "I have the self-confidence necessary to try different ways of behaving", text_bn: "আমার আচরণের বিভিন্ন উপায় চেষ্টা করার জন্য প্রয়োজনীয় আত্মবিশ্বাস আছে।", text_hi: "मुझमें व्यवहार के विभिन्न तरीकों को आजमाने के लिए आवश्यक आत्मविश्वास है।", text_mr: "माझ्याकडे वागण्याच्या विविध पद्धती वापरून पाहण्यासाठी आवश्यक असलेला आत्मविश्वास आहे.", isReverse: false },
    ]
  },
  {
    id: "gaene",
    title: "Generalized Acceptance of EvolutioN Evaluation (GAENE)",
    title_bn: "বিবর্তন মূল্যায়নের সাধারণ স্বীকৃতি (GAENE)",
    title_hi: "क्रमिक विकास स्वीकृति मूल्यांकन (GAENE)",
    title_mr: "उत्क्रांती स्वीकृती मूल्यमापन (GAENE)",
    description: "For the following items, please indicate your agreement/disagreement with the given statements:",
    description_bn: "নিম্নলিখিত আইটেমগুলির জন্য, অনুগ্রহ করে প্রদত্ত বিবৃতিগুলির সাথে আপনার সম্মতি/অসম্মতি নির্দেশ করুন:",
    description_hi: "निम्नलिखित कथनों के लिए, कृपया दिए गए कथनों से अपनी सहमति/असहमति बताएं:",
    description_mr: "खालील बाबींसाठी, कृपया दिलेल्या विधानांशी तुमची सहमती/असहमती दर्शवा:",
    scaleMin: 1,
    scaleMax: 5,
    scale: [
      { label: "Strongly disagree", label_bn: "সম্পূর্ণ দ্বিমত", label_hi: "पूर्णतः असहमत", label_mr: "पूर्णपणे असहमत", value: 1 },
      { label: "Disagree", label_bn: "দ্বিমত", label_hi: "असहमत", label_mr: "असहमत", value: 2 },
      { label: "I don't know / no opinion", label_bn: "আমি জানি না / কোনো মতামত নেই", label_hi: "मुझे पता नहीं / कोई राय नहीं", label_mr: "मला माहित नाही / कोणतेही मत नाही", value: 3 },
      { label: "Agree", label_bn: "একমত", label_hi: "सहमत", label_mr: "सहमत", value: 4 },
      { label: "Strongly Agree", label_bn: "সম্পূর্ণ একমত", label_hi: "पूर्णतः सहमत", label_mr: "पूर्णपणे सहमत", value: 5 },
    ],
    orderType: "buildup",
    scoringType: "mean",
    feedbackTemplate: "Your GAENE score (range 1.0 to 5.0) is {score}.",
    items: [
      { id: "q1", text: "Everyone should understand evolution.", text_bn: "সবারই বিবর্তন সম্পর্কে বোঝা উচিত।", text_hi: "हर किसी को क्रमिक विकास समझना चाहिए।", text_mr: "प्रत्येकाने उत्क्रांती समजून घेतली पाहिजे.", isReverse: false },
      { id: "q2", text: "It is important to let people know about how strong the evidence that supports evolution is.", text_bn: "বিবর্তনকে সমর্থনকারী প্রমাণগুলি কতটা শক্তিশালী তা লোকেদের জানানো গুরুত্বপূর্ণ।", text_hi: "लोगों को यह बताना महत्वपूर्ण है कि क्रमिक विकास का समर्थन करने वाले प्रमाण कितने मजबूत हैं।", text_mr: "उत्क्रांतीला समर्थन देणारे पुरावे किती भक्कम आहेत हे लोकांना सांगणे महत्त्वाचे आहे.", isReverse: false },
      { id: "q3", text: "Some parts of evolution theory could be true.", text_bn: "বিবর্তন তত্ত্বের কিছু অংশ সত্য হতে পারে।", text_hi: "क्रमिक विकास सिद्धांत के कुछ भाग सत्य हो सकते हैं।", text_mr: "उत्क्रांती सिद्धांताचे काही भाग खरे असू शकतात.", isReverse: false },
      { id: "q4", text: "Evolutionary theory applies to all plants and animals, including humans.", text_bn: "বিবর্তনীয় তত্ত্ব মানুষ সহ সমস্ত উদ্ভিদ এবং প্রাণীর ক্ষেত্রে প্রযোজ্য।", text_hi: "क्रमिक विकास का सिद्धांत इंसानों सहित सभी पौधों और जानवरों पर लागू होता है।", text_mr: "उत्क्रांतीचा सिद्धांत मानवासह सर्व वनस्पती आणि प्राण्यांना लागू होतो.", isReverse: false },
      { id: "q5", text: "People who plan to become biologists need to understand evolution.", text_bn: "যারা জীববিজ্ঞানী হওয়ার পরিকল্পনা করেন তাদের বিবর্তন বুঝতে হবে।", text_hi: "जो लोग जीवविज्ञानी बनने की योजना बनाते हैं उन्हें क्रमिक विकास को समझना आवश्यक है।", text_mr: "जे जीवशास्त्रज्ञ बनण्याचा विचार करतात त्यांना उत्क्रांती समजून घेणे आवश्यक आहे.", isReverse: false },
      { id: "q6", text: "I would be willing to argue in favor of evolutionary in a public forum such as a school club, church group, or meeting of public school parents.", text_bn: "আমি স্কুল ক্লাব, চার্চ গ্রুপ বা পাবলিক স্কুলের অভিভাবকদের মিটিংয়ের মতো কোনো পাবলিক ফোরামে বিবর্তনের পক্ষে যুক্তি দিতে ইচ্ছুক হব।", text_hi: "मैं किसी सार्वजनिक मंच जैसे स्कूल क्लब या अभिभावकों की बैठक में क्रमिक विकास के पक्ष में बहस करने को तैयार रहूँगा।", text_mr: "मी शाळा क्लब किंवा पालकांच्या बैठकीसारख्या सार्वजनिक मंचावर उत्क्रांतीच्या बाजूने युक्तिवाद करण्यास तयार असेन.", isReverse: false },
      { id: "q7", text: "Simple organisms such as bacteria change over time.", text_bn: "ব্যাকটেরিয়ার মতো সাধারণ জীব সময়ের সাথে পরিবর্তিত হয়।", text_hi: "बैक्टीरिया जैसे सरल जीव समय के साथ बदलते हैं।", text_mr: "बॅक्टेरियासारखे साधे जीव कालांतराने बदलतात.", isReverse: false },
      { id: "q8", text: "Nothing in biology makes sense without evolution.", text_bn: "বিবর্তন ছাড়া জীববিজ্ঞানের কোনো কিছুরই অর্থ হয় না।", text_hi: "क्रमिक विकास के बिना जीव विज्ञान में किसी भी बात का कोई अर्थ नहीं है।", text_mr: "उत्क्रांतीशिवाय जीवशास्त्रात कशालाही अर्थ नाही.", isReverse: false },
      { id: "q9", text: "Understanding evolution helps me understand the other parts of biology.", text_bn: "বিবর্তন বোঝা আমাকে জীববিজ্ঞানের অন্যান্য অংশ বুঝতে সাহায্য করে।", text_hi: "क्रमिक विकास को समझने से मुझे जीव विज्ञान के अन्य भागों को समझने में मदद मिलती है।", text_mr: "उत्क्रांती समजून घेतल्याने मला जीवशास्त्राचे इतर भाग समजण्यास मदत होते.", isReverse: false },
      { id: "q10", text: "I would be willing to argue in favor of evolution in a small group of friends.", text_bn: "আমি বন্ধুদের একটি ছোট গ্রুপে বিবর্তনের পক্ষে যুক্তি দিতে ইচ্ছুক হব।", text_hi: "मैं दोस्तों के एक छोटे समूह में क्रमिक विकास के पक्ष में तर्क करने को तैयार रहूँगा।", text_mr: "मी मित्रांच्या लहान गटामध्ये उत्क्रांतीच्या बाजूने युक्तिवाद करण्यास तयार असेन.", isReverse: false },
      { id: "q11", text: "Evolution is a good explanation of how humans first emerged on the earth.", text_bn: "বিবর্তন হলো পৃথিবীতে মানুষ কীভাবে প্রথম আবির্ভূত হয়েছিল তার একটি ভালো ব্যাখ্যা।", text_hi: "पृथ्वी पर मानव पहली बार कैसे प्रकट हुए, इसकी क्रमिक विकास एक अच्छी व्याख्या है।", text_mr: "पृथ्वीवर मानव पहिल्यांदा कसा अस्तित्वात आला याचे उत्क्रांती हे एक उत्तम स्पष्टीकरण आहे.", isReverse: false },
      { id: "q12", text: "Evolution is a scientific fact.", text_bn: "বিবর্তন একটি বৈজ্ঞানিক সত্য।", text_hi: "क्रमिक विकास एक वैज्ञानिक तथ्य है।", text_mr: "उत्क्रांती हे एक वैज्ञानिक सत्य आहे.", isReverse: false },
      { id: "q13", text: "Evolution is a good explanation of how new species arise.", text_bn: "কীভাবে নতুন প্রজাতির উদ্ভব হয় তার একটি ভালো ব্যাখ্যা হলো বিবর্তন।", text_hi: "नई प्रजातियां कैसे उत्पन्न होती हैं, इसकी क्रमिक विकास एक अच्छी व्याख्या है।", text_mr: "नवीन प्रजाती कशा निर्माण होतात याचे उत्क्रांती हे एक उत्तम स्पष्टीकरण आहे.", isReverse: false },
    ]
  },
  {
    id: "mate",
    title: "Measure of Acceptance of the Theory of Evolution (MATE)",
    title_bn: "বিবর্তন তত্ত্বের স্বীকৃতির পরিমাপ (MATE)",
    title_hi: "क्रमिक विकास सिद्धांत की स्वीकृति का माप (MATE)",
    title_mr: "उत्क्रांती सिद्धांताच्या स्वीकृतीचे मापन (MATE)",
    description: "For the following items, please indicate your agreement/disagreement with the given statements:",
    description_bn: "নিম্নলিখিত আইটেমগুলির জন্য, অনুগ্রহ করে প্রদত্ত বিবৃতিগুলির সাথে আপনার সম্মতি/অসম্মতি নির্দেশ করুন:",
    description_hi: "निम्नलिखित कथनों के लिए, कृपया दिए गए कथनों से अपनी सहमति/असहमति बताएं:",
    description_mr: "खालील बाबींसाठी, कृपया दिलेल्या विधानांशी तुमची सहमती/असहमती दर्शवा:",
    scaleMin: 1,
    scaleMax: 5,
    scale: [
      { label: "Strongly agree", label_bn: "সম্পূর্ণ একমত", label_hi: "पूर्णतः सहमत", label_mr: "पूर्णपणे सहमत", value: 5 },
      { label: "Agree", label_bn: "একমত", label_hi: "सहमत", label_mr: "सहमत", value: 4 },
      { label: "Undecided", label_bn: "অনিশ্চিত", label_hi: "अनिर्णित", label_mr: "अनिर्णित", value: 3 },
      { label: "Disagree", label_bn: "দ্বিমত", label_hi: "असहमत", label_mr: "असहमत", value: 2 },
      { label: "Strongly disagree", label_bn: "সম্পূর্ণ দ্বিমত", label_hi: "पूर्णतः असहमत", label_mr: "पूर्णपणे असहमत", value: 1 },
    ],
    orderType: "buildup",
    scoringType: "sum",
    feedbackTemplate: "Your score on the Measure of Acceptance of the Theory of Evolution (MATE) is {score} points. Scores are between 20 (low) to 100 (high level of acceptance).",
    items: [
      { id: "q1", text: "Organisms existing today are the result of evolutionary processes that have occurred over millions of years", text_bn: "বর্তমানে বিদ্যমান জীবগুলি লাখ লাখ বছর ধরে ঘটে আসা বিবর্তনীয় প্রক্রিয়ার ফল।", text_hi: "आज मौजूद जीव लाखों वर्षों में हुई क्रमिक विकास प्रक्रियाओं का परिणाम हैं।", text_mr: "आज अस्तित्वात असलेले जीव हे लाखो वर्षांत झालेल्या उत्क्रांती प्रक्रियेचा परिणाम आहेत.", isReverse: false },
      { id: "q2", text: "The theory of evolution is incapable of being scientifically tested", text_bn: "বিবর্তন তত্ত্বটি বৈজ্ঞানিকভাবে পরীক্ষা করা অসম্ভব।", text_hi: "क्रमिक विकास के सिद्धांत का वैज्ञानिक रूप से परीक्षण करना असंभव है।", text_mr: "उत्क्रांती सिद्धांताची वैज्ञानिकदृष्ट्या चाचणी घेणे अशक्य आहे.", isReverse: true },
      { id: "q3", text: "Modern humans are the product of evolutionary processes that have occurred over millions of years", text_bn: "আধুনিক মানুষ হলো লাখ লাখ বছর ধরে ঘটে আসা বিবর্তনীয় প্রক্রিয়ার ফল।", text_hi: "आधुनिक मानव लाखों वर्षों में हुई क्रमिक विकास प्रक्रियाओं का उत्पाद हैं।", text_mr: "आधुनिक मानव हे लाखो वर्षांत घडलेल्या उत्क्रांती प्रक्रियेचे फलित आहेत.", isReverse: false },
      { id: "q4", text: "The theory of evolution is based on speculation and not valid scientific observation and testing", text_bn: "বিবর্তন তত্ত্ব অনুমানের ওপর ভিত্তি করে তৈরি এবং এটি বৈধ বৈজ্ঞানিক পর্যবেক্ষণ এবং পরীক্ষার ওপর ভিত্তি করে নয়।", text_hi: "क्रमिक विकास का सिद्धांत अटकलों पर आधारित है, वैध वैज्ञानिक अवलोकन और परीक्षण पर नहीं।", text_mr: "उत्क्रांतीचा सिद्धांत अनुमानांवर आधारित आहे, वैध वैज्ञानिक निरीक्षण आणि चाचणीवर नाही.", isReverse: true },
      { id: "q5", text: "Most scientists accept evolutionary theory to be a scientifically valid theory", text_bn: "বেশিরভাগ বিজ্ঞানী বিবর্তনীয় তত্ত্বকে একটি বৈজ্ঞানিকভাবে বৈধ তত্ত্ব হিসেবে গ্রহণ করেন।", text_hi: "अधिकांश वैज्ञानिक क्रमिक विकास सिद्धांत को एक वैज्ञानिक रूप से वैध सिद्धांत मानते हैं।", text_mr: "बहुतेक शास्त्रज्ञ उत्क्रांती सिद्धांताला वैज्ञानिकदृष्ट्या वैध सिद्धांत मानतात.", isReverse: false },
      { id: "q6", text: "The available data are ambiguous (unclear) as to whether evolution actually occurs", text_bn: "বিবর্তন আসলেই ঘটে কি না সে বিষয়ে উপলব্ধ ডেটাগুলি অস্পষ্ট (অস্পষ্ট)।", text_hi: "उपलब्ध डेटा अस्पष्ट है कि क्या वास्तव में क्रमिक विकास होता है।", text_mr: "उत्क्रांती खरोखर घडते की नाही याबद्दल उपलब्ध माहिती अस्पष्ट आहे.", isReverse: true },
      { id: "q7", text: "The age of the earth is less than 20,000 years", text_bn: "পৃথিবীর বয়স ২০,০০০ বছরেরও কম।", text_hi: "पृथ्वी की आयु 20,000 वर्ष से कम है।", text_mr: "पृथ्वीचे वय २०,००० वर्षांपेक्षा कमी आहे.", isReverse: true },
      { id: "q8", text: "There is a significant body of data that supports evolutionary theory", text_bn: "বিবর্তনীয় তত্ত্বকে সমর্থন করার জন্য উল্লেখযোগ্য পরিমাণে ডেটা রয়েছে।", text_hi: "पर्याप्त डेटा मौजूद है जो क्रमिक विकास सिद्धांत का समर्थन करता है।", text_mr: "उत्क्रांती सिद्धांताला समर्थन देणारा महत्त्वपूर्ण डेटा उपलब्ध आहे.", isReverse: false },
      { id: "q9", text: "Organisms exist today in essentially the same form in which they always have", text_bn: "বর্তমানে বিদ্যমান জীবগুলি মূলত একই রূপে আছে যেভাবে তারা সবসময় ছিল।", text_hi: "जीव आज अनिवार्य रूप से उसी रूप में मौजूद हैं जिसमें वे हमेशा रहे हैं।", text_mr: "जीव आज मुळात त्याच रूपात अस्तित्वात आहेत ज्या रूपात ते नेहमी होते.", isReverse: true },
      { id: "q10", text: "Evolution in not a scientifically valid theory", text_bn: "বিবর্তন কোনো বৈজ্ঞানিকভাবে বৈধ তত্ত্ব নয়।", text_hi: "क्रमिक विकास वैज्ञानिक रूप से वैध सिद्धांत नहीं है।", text_mr: "उत्क्रांती हा वैज्ञानिकदृष्ट्या वैध सिद्धांत नाही.", isReverse: true },
      { id: "q11", text: "The age of the earth is at least 4 billion years", text_bn: "পৃথিবীর বয়স অন্তত ৪ বিলিয়ন বছর।", text_hi: "पृथ्वी की आयु कम से कम 4 अरब वर्ष है।", text_mr: "पृथ्वीचे वय किमान ४ अब्ज वर्षे आहे.", isReverse: false },
      { id: "q12", text: "Current evolutionary theory is the result of sound scientific research and methodology", text_bn: "বর্তমান বিবর্তনীয় তত্ত্ব হলো সুনিপুণ বৈজ্ঞানিক গবেষণা এবং পদ্ধতির ফল।", text_hi: "वर्तमान क्रमिक विकास सिद्धांत ठोस वैज्ञानिक अनुसंधान और कार्यप्रणाली का परिणाम है।", text_mr: "सध्याचा उत्क्रांती सिद्धांत हा सखोल वैज्ञानिक संशोधन आणि पद्धतींचा परिणाम आहे.", isReverse: false },
      { id: "q13", text: "Evolutionary theory generates testable predictions with respect to the characteristics of life", text_bn: "বিবর্তনীয় তত্ত্ব জীবনের বৈশিষ্ট্যগুলির ক্ষেত্রে পরীক্ষাযোগ্য ভবিষ্যদ্বাণী তৈরি করে।", text_hi: "क्रमिक विकास सिद्धांत जीवन की विशेषताओं के संबंध में परीक्षण योग्य भविष्यवाणियां उत्पन्न करता है।", text_mr: "उत्क्रांती सिद्धांत जीवनाच्या वैशिष्ट्यांच्या संदर्भात चाचणीयोग्य भाकिते निर्माण करतो.", isReverse: false },
      { id: "q14", text: "The theory of evolution cannot be correct since it disagrees with the Biblical account of creation", text_bn: "বিবর্তন তত্ত্বটি সঠিক হতে পারে না কারণ এটি সৃষ্টির বাইবেলের বিবরণের সাথে একমত নয়।", text_hi: "क्रमिक विकास का सिद्धांत सही नहीं हो सकता क्योंकि यह धार्मिक सृष्टि कथा से असहमत है।", text_mr: "उत्क्रांतीचा सिद्धांत योग्य असू शकत नाही कारण तो निर्मितीच्या धार्मिक वर्णनाशी विसंगत आहे.", isReverse: true },
      { id: "q15", text: "Humans exist today in essentially the same form in which they always have", text_bn: "বর্তমানে মানুষ মূলত একই রূপে আছে যেভাবে তারা সবসময় ছিল।", text_hi: "मानव आज अनिवार्य रूप से उसी रूप में मौजूद हैं जिसमें वे हमेशा रहे हैं।", text_mr: "मानव आज मूलतः त्याच रूपात अस्तित्वात आहेत ज्या रूपात ते नेहमी होते.", isReverse: true },
      { id: "q16", text: "Evolutionary theory is supported by factual historical and laboratory data", text_bn: "বিবর্তনীয় তত্ত্ব বাস্তব ঐতিহাসিক এবং ল্যাবরেটরি ডেটা দ্বারা সমর্থিত।", text_hi: "क्रमिक विकास सिद्धांत तथ्यात्मक ऐतिहासिक और प्रयोगशाला डेटा द्वारा समर्थित है।", text_mr: "उत्क्रांती सिद्धांत वास्तव ऐतिहासिक आणि प्रयोगशाळेतील डेटाद्वारे समर्थित आहे.", isReverse: false },
      { id: "q17", text: "Much of the scientific community doubts if evolution occurs", text_bn: "বৈজ্ঞানিক সম্প্রদায়ের বেশিরভাগই বিবর্তন ঘটে কি না তা নিয়ে সন্দেহ পোষণ করে।", text_hi: "वैज्ञानिक समुदाय का एक बड़ा हिस्सा इस बात पर संदेह करता है कि क्या क्रमिक विकास होता है।", text_mr: "वैज्ञानिक समुदायाचा बराचसा भाग उत्क्रांती घडते की नाही यावर शंका घेतो.", isReverse: true },
      { id: "q18", text: "The theory of evolution brings meaning to the diverse characteristics and behaviors observed in living forms", text_bn: "বিবর্তন তত্ত্ব জীবন্ত রূপগুলিতে পরিলক্ষিত বিভিন্ন বৈশিষ্ট্য এবং আচরণের অর্থ বহন করে।", text_hi: "क्रमिक विकास सिद्धांत जीवित रूपों में देखे जाने वाले विविध लक्षणों और व्यवहारों को अर्थ प्रदान करता है।", text_mr: "उत्क्रांती सिद्धांत सजीवांमध्ये दिसून येणाऱ्या विविध वैशिष्ट्यांना आणि वर्तनांना अर्थ देतो.", isReverse: false },
      { id: "q19", text: "With few exceptions, organisms on earth came into existence at about the same time", text_bn: "কিছু ব্যতিক্রম ছাড়া, পৃথিবীতে জীবগুলি প্রায় একই সময়ে অস্তিত্ব লাভ করেছে।", text_hi: "कुछ अपवादों को छोड़कर, पृथ्वी पर जीव लगभग एक ही समय में अस्तित्व में आए।", text_mr: "काही अपवाद वगळता, पृथ्वीवरील जीव साधारणपणे एकाच वेळी अस्तित्वात आले.", isReverse: true },
      { id: "q20", text: "Evolution is a scientifically valid theory", text_bn: "বিবর্তন একটি বৈজ্ঞানিকভাবে বৈধ তত্ত্ব।", text_hi: "क्रमिक विकास एक वैज्ञानिक रूप से वैध सिद्धांत है।", text_mr: "उत्क्रांती हा वैज्ञानिकदृष्ट्या वैध सिद्धांत आहे.", isReverse: false },
    ]
  },
  {
    id: "sbs",
    title: "Supernatural Belief Scale (SBS)",
    title_bn: "অতিপ্রাকৃতিক বিশ্বাস স্কেল (SBS)",
    title_hi: "अलौकिक विश्वास पैमाना (SBS)",
    title_mr: "अलौकिक विश्वास प्रमाण (SBS)",
    description: "Please indicate your agreement with the following statements. Note: The scale runs from strongly disagree to strongly agree, you need to choose the level agreement that matches your personal beliefs.",
    description_bn: "অনুগ্রহ করে নিম্নলিখিত বিবৃতিগুলির সাথে আপনার সম্মতি নির্দেশ করুন। দ্রষ্টব্য: স্কেলটি সম্পূর্ণ দ্বিমত থেকে সম্পূর্ণ একমত পর্যন্ত চলে, আপনাকে আপনার ব্যক্তিগত বিশ্বাসের সাথে মেলে এমন চুক্তি নির্বাচন করতে হবে।",
    description_hi: "कृपया निम्नलिखित कथनों से अपनी सहमति बताएं (-4 पूर्णतः असहमत से 4 पूर्णतः सहमत तक):",
    description_mr: "कृपया खालील विधानांशी तुमची सहमती दर्शवा (-४ पूर्णपणे असहमत ते ४ पूर्णपणे सहमत पर्यंत):",
    scaleMin: -4,
    scaleMax: 4,
    scale: [
      { label: "strongly disagree (-4)", label_bn: "সম্পূর্ণ দ্বিমত (-৪)", label_hi: "पूर्णतः असहमत (-4)", label_mr: "पूर्णपणे असहमत (-४)", value: -4 },
      { label: "-3", label_bn: "-৩", label_hi: "-3", label_mr: "-३", value: -3 },
      { label: "-2", label_bn: "-২", label_hi: "-2", label_mr: "-२", value: -2 },
      { label: "-1", label_bn: "-১", label_hi: "-1", label_mr: "-१", value: -1 },
      { label: "neither agree nor disagree (0)", label_bn: "একমত বা দ্বিমত কোনোটিই নয় (০)", label_hi: "न सहमत न असहमत (0)", label_mr: "सहमत किंवा असहमत नाही (०)", value: 0 },
      { label: "1", label_bn: "১", label_hi: "1", label_mr: "१", value: 1 },
      { label: "2", label_bn: "২", label_hi: "2", label_mr: "२", value: 2 },
      { label: "3", label_bn: "৩", label_hi: "3", label_mr: "३", value: 3 },
      { label: "strongly agree (4)", label_bn: "সম্পূর্ণ একমত (৪)", label_hi: "पूर्णतः सहमत (4)", label_mr: "पूर्णपणे सहमत (४)", value: 4 },
    ],
    orderType: "buildup",
    scoringType: "mean",
    feedbackTemplate: "The supernatural belief scale has a possible range from -4 (no supernatural beliefs at all) to 4 (strong supernatural beliefs). Your score on the supernatural belief scale is {score}.",
    items: [
      { id: "q1", text: "There exists an all-powerful, all-knowing, loving God.", text_bn: "একটি সর্বশক্তিমান, সর্বজ্ঞ, প্রেমময় ঈশ্বর বিদ্যমান।", text_hi: "एक सर्वशक्तिमान, सर्वज्ञानी, प्रेममय ईश्वर का अस्तित्व है।", text_mr: "एक सर्वशक्तिमान, सर्वज्ञानी, प्रेमळ देव अस्तित्वात आहे.", isReverse: false },
      { id: "q2", text: "There exists an evil personal spiritual being, whom we might call the Devil.", text_bn: "একটি মন্দ আত্মিক সত্ত্বা বিদ্যমান, যাকে আমরা শয়তান বলতে পারি।", text_hi: "एक दुष्ट आध्यात्मिक शक्ति का अस्तित्व है, जिसे हम शैतान कह सकते हैं।", text_mr: "एक दुष्ट आध्यात्मिक शक्ती अस्तित्वात आहे, ज्याला आपण सैतान म्हणू शकतो.", isReverse: false },
      { id: "q3", text: "There exist good personal spiritual beings, whom we might call angels.", text_bn: "ভালো আত্মিক সত্ত্বা বিদ্যমান, যাদের আমরা ফেরেশতা বা দেবদূত বলতে পারি।", text_hi: "अच्छे आध्यात्मिक प्राणी मौजूद हैं, जिन्हें हम देवदूत कह सकते हैं।", text_mr: "चांगले आध्यात्मिक प्राणी अस्तित्वात आहेत, ज्यांना आपण देवदूत म्हणू शकतो.", isReverse: false },
      { id: "q4", text: "There exist evil, personal spiritual beings, whom we might call demons.", text_bn: "মন্দ আত্মিক সত্ত্বা বিদ্যমান, যাদের আমরা রাক্ষস বা অপদেবতা বলতে পারি।", text_hi: "दुष्ट आध्यात्मिक प्राणी मौजूद हैं, जिन्हें हम असुर या राक्षस कह सकते हैं।", text_mr: "वाईट आध्यात्मिक प्राणी अस्तित्वात आहेत, ज्यांना आपण पिशाच किंवा राक्षस म्हणू शकतो.", isReverse: false },
      { id: "q5", text: "Human beings have immaterial, immortal souls.", text_bn: "মানুষের জড়হীন, অমর আত্মা আছে।", text_hi: "मनुष्यों के पास अभौतिक, अमर आत्माएं होती हैं।", text_mr: "मानवामध्ये अभौतिक, अमर आत्मा असतो.", isReverse: false },
      { id: "q6", text: "There is a spiritual realm besides the physical one.", text_bn: "ভৌতিক জগতের পাশাপাশি একটি আধ্যাত্মিক জগৎ রয়েছে।", text_hi: "भौतिक दुनिया के अलावा एक आध्यात्मिक संसार भी है।", text_mr: "भौतिक जगाव्यतिरिक्त एक आध्यात्मिक जग देखील अस्तित्वात आहे.", isReverse: false },
      { id: "q7", text: "Some people will be rewarded in an afterlife when they die.", text_bn: "কিছু মানুষ মারা গেলে পরকালে পুরস্কৃত হবে।", text_hi: "कुछ लोगों को मरने के बाद परलोक में पुरस्कृत किया जाएगा।", text_mr: "काही लोकांना मृत्यूनंतर परलोकात बक्षीस दिले जाईल.", isReverse: false },
      { id: "q8", text: "Some people will be punished in an afterlife when they die.", text_bn: "কিছু মানুষ মারা গেলে পরকালে শাস্তি পাবে।", text_hi: "कुछ लोगों को मरने के बाद परलोक में दंडित किया जाएगा।", text_mr: "काही लोकांना मृत्यूनंतर परलोकात शिक्षा दिली जाईल.", isReverse: false },
      { id: "q9", text: "Miracles—divinely-caused events that have no natural explanation—can and do happen.", text_bn: "অলৌকিক ঘটনা - ঐশ্বরিক ঘটনা যার কোনো প্রাকৃতিক ব্যাখ্যা নেই - ঘটতে পারে এবং ঘটে।", text_hi: "चमत्कार - ईश्वरीय घटनाएं जिनका कोई प्राकृतिक स्पष्टीकरण नहीं है - हो सकते हैं और होते हैं।", text_mr: "चमत्कार - दैवी घटना ज्यांना कोणतेही नैसर्गिक स्पष्टीकरण नाही - घडू शकतात आणि घडतात.", isReverse: false },
      { id: "q10", text: "There are individuals who are messengers of God and/or can foresee the future.", text_bn: "এমন ব্যক্তি আছেন যারা ঈশ্বরের বার্তাবাহক এবং/অথবা ভবিষ্যৎ দেখতে পারেন।", text_hi: "ऐसे व्यक्ति हैं जो ईश्वर के संदेशवाहक हैं और/या भविष्य देख सकते हैं।", text_mr: "अशा व्यक्ती आहेत ज्या देवाचे दूत आहेत आणि/किंवा भविष्य पाहू शकतात.", isReverse: false },
    ]
  },
  {
    id: "skep",
    title: "Skepticism towards advertisements (SKEP)",
    title_bn: "বিজ্ঞাপনের প্রতি সংশয় (SKEP)",
    title_hi: "विज्ञापनों के प्रति संशय (SKEP)",
    title_mr: "जाहिरातींबद्दल संशय (SKEP)",
    description: "Select for each of the statements below how much you agree (ranging from strongly agree to strongly disagree).",
    description_bn: "নীচের প্রতিটি বিবৃতির জন্য নির্বাচন করুন আপনি কতটা একমত (সম্পূর্ণ একমত থেকে সম্পূর্ণ দ্বিমত পর্যন্ত)।",
    description_hi: "नीचे दिए गए प्रत्येक कथन के लिए चुनें कि आप कितना सहमत हैं (पूर्णतः सहमत से पूर्णतः असहमत तक)।",
    description_mr: "खालील प्रत्येक विधानासाठी आपण किती सहमत आहात ते निवडा (पूर्णपणे सहमत ते पूर्णपणे असहमत).",
    scaleMin: 1,
    scaleMax: 5,
    scale: [
      { label: "strongly agree", label_bn: "সম্পূর্ণ একমত", label_hi: "पूर्णतः सहमत", label_mr: "पूर्णपणे सहमत", value: 5 },
      { label: "agree", label_bn: "একমত", label_hi: "सहमत", label_mr: "सहमत", value: 4 },
      { label: "neutral", label_bn: "নিরপেক্ষ", label_hi: "तटस्थ", label_mr: "तटस्थ", value: 3 },
      { label: "disagree", label_bn: "দ্বিমত", label_hi: "असहमत", label_mr: "असहमत", value: 2 },
      { label: "strongly disagree", label_bn: "সম্পূর্ণ দ্বিমত", label_hi: "पूर्णतः असहमत", label_mr: "पूर्णपणे असहमत", value: 1 },
    ],
    orderType: "normal",
    scoringType: "sum",
    feedbackTemplate: "The possible range on the SKEP runs from 9 to 45 points. The higher the score, the more skeptical you are towards advertising. Your score on the SKEP is {score}. Check the accompanying PsyToolkit website for population averages.",
    items: [
      { id: "q1", text: "We can depend on getting the truth in most advertising.", text_bn: "আমরা বেশিরভাগ বিজ্ঞাপনে সত্য পাওয়ার ওপর নির্ভর করতে পারি।", text_hi: "हम अधिकांश विज्ञापनों में सच्चाई प्राप्त करने पर भरोसा कर सकते हैं।", text_mr: "आम्ही बहुतेक जाहिरातींमध्ये खरेपणा मिळण्यावर विश्वास ठेवू शकतो.", isReverse: false },
      { id: "q2", text: "Advertising's aim is to inform the consumer.", text_bn: "বিজ্ঞাপনের উদ্দেশ্য হলো ভোক্তাকে জানানো।", text_hi: "विज्ञापन का उद्देश्य उपभोक्ता को सूचित करना है।", text_mr: "जाहिरातीचा उद्देश ग्राहकाला माहिती देणे हा आहे.", isReverse: false },
      { id: "q3", text: "I believe advertising is not informative.", text_bn: "আমি বিশ্বাস করি বিজ্ঞাপন তথ্যবহুল নয়।", text_hi: "मेरा मानना है कि विज्ञापन ज्ञानवर्धक या सूचनात्मक नहीं होते हैं।", text_mr: "माझे मत आहे की जाहिराती माहितीपूर्ण नसतात.", isReverse: true },
      { id: "q4", text: "Advertising is generally truthful.", text_bn: "বিজ্ঞাপন সাধারণত সত্যবাদী হয়।", text_hi: "विज्ञापन आम तौर पर सच्चे होते हैं।", text_mr: "जाहिराती सामान्यतः खऱ्या असतात.", isReverse: false },
      { id: "q5", text: "Advertising is not a reliable source of information about the quality and performance of products.", text_bn: "পণ্যের গুণমান এবং কার্যকারিতা সম্পর্কে তথ্যের একটি নির্ভরযোগ্য উৎস বিজ্ঞাপন নয়।", text_hi: "उत्पादों की गुणवत्ता और प्रदर्शन के बारे में विज्ञापन जानकारी का एक विश्वसनीय स्रोत नहीं है।", text_mr: "उत्पादनांची गुणवत्ता आणि कामगिरीबद्दल माहितीचा एक विश्वासार्ह स्रोत जाहिरात नाही.", isReverse: true },
      { id: "q6", text: "Advertising is truth well told.", text_bn: "বিজ্ঞাপন হলো সত্য যা ভালোভাবে বলা হয়েছে।", text_hi: "विज्ञापन अच्छी तरह से कही गई सच्चाई है।", text_mr: "जाहिरात म्हणजे चांगल्या प्रकारे सांगितलेले सत्य आहे.", isReverse: false },
      { id: "q7", text: "In general, advertising does not present a true picture of the product being advertised.", text_bn: "সাধারণত, বিজ্ঞাপন বিজ্ঞাপিত পণ্যের একটি সত্য চিত্র উপস্থাপন করে না।", text_hi: "सामान्य तौर पर, विज्ञापन विज्ञापित उत्पाद की सच्ची तस्वीर पेश नहीं करता है।", text_mr: "सर्वसाधारणपणे, जाहिरात जाहिरात केलेल्या उत्पादनाचे खरे चित्र सादर करत नाही.", isReverse: true },
      { id: "q8", text: "I feel I've been accurately informed after viewing most advertisements.", text_bn: "আমার মনে হয় বেশিরভাগ বিজ্ঞাপন দেখার পর আমি সঠিকভাবে অবহিত হয়েছি।", text_hi: "मुझे लगता है कि अधिकांश विज्ञापन देखने के बाद मुझे सटीक जानकारी मिली है।", text_mr: "मला वाटते की बहुतेक जाहिराती पाहिल्यानंतर मला अचूक माहिती मिळाली आहे.", isReverse: false },
      { id: "q9", text: "Most advertising does not provide consumers with essential information.", text_bn: "বেশিরভাগ বিজ্ঞাপন ভোক্তাদের প্রয়োজনীয় তথ্য প্রদান করে না।", text_hi: "अधिकांश विज्ञापन उपभोक्ताओं को आवश्यक जानकारी प्रदान नहीं करते हैं।", text_mr: "बहुतेक जाहिराती ग्राहकांना आवश्यक माहिती पुरवत नाहीत.", isReverse: true },
    ]
  },
  {
    id: "tsis",
    title: "Social Intelligence (Tromsø Social Intelligence Scale, TSIS)",
    title_bn: "সামাজিক বুদ্ধিমত্তা (ট্রোমসো সোশ্যাল ইন্টেলিজেন্স স্কেল, TSIS)",
    title_hi: "सामाजिक बुद्धिमत्ता (ट्रोम्सो सोशल इंटेलिजेंस स्केल, TSIS)",
    title_mr: "सामाजिक बुद्धिमत्ता (ट्रोम्सो सोशल इंटेलिजन्स स्केल, TSIS)",
    description: "For each item, indicate how well it describes you on a scale from 1 (describes me extremely poorly) to 7 (describes me extremely well):",
    description_bn: "প্রতিটি আইটেমের জন্য, নির্দেশ করুন এটি আপনাকে কতটা ভালোভাবে বর্ণনা করে ১ (আমাকে অত্যন্ত খারাপভাবে বর্ণনা করে) থেকে ৭ (আমাকে অত্যন্ত ভালোভাবে বর্ণনা করে) এর স্কেলে:",
    description_hi: "प्रत्येक कथन के लिए, 1 (मेरा बहुत खराब वर्णन करता है) से 7 (मेरा बहुत अच्छी तरह वर्णन करता है) के पैमाने पर इंगित करें:",
    description_mr: "प्रत्येक विधानासाठी, १ (माझे वर्णन अत्यंत वाईट रीतीने करते) ते ७ (माझे वर्णन अत्यंत चांगल्या प्रकारे करते) या स्केलवर सूचित करा:",
    scaleMin: 1,
    scaleMax: 7,
    scale: [
      { label: "1 (Describes me extremely poorly)", label_bn: "১ (আমাকে অত্যন্ত খারাপভাবে বর্ণনা করে)", label_hi: "1 (मेरा बहुत खराब वर्णन करता है)", label_mr: "१ (माझे वर्णन अत्यंत वाईट रीतीने करते)", value: 1 },
      { label: "2", label_bn: "২", label_hi: "2", label_mr: "२", value: 2 },
      { label: "3", label_bn: "৩", label_hi: "3", label_mr: "३", value: 3 },
      { label: "4", label_bn: "৪", label_hi: "4", label_mr: "४", value: 4 },
      { label: "5", label_bn: "৫", label_hi: "5", label_mr: "५", value: 5 },
      { label: "6", label_bn: "৬", label_hi: "6", label_mr: "६", value: 6 },
      { label: "7 (Describes me extremely well)", label_bn: "৭ (আমাকে অত্যন্ত ভালোভাবে বর্ণনা করে)", label_hi: "7 (मेरा बहुत अच्छी तरह वर्णन करता है)", label_mr: "७ (माझे वर्णन अत्यंत चांगल्या प्रकारे करते)", value: 7 },
    ],
    orderType: "normal",
    scoringType: "tsis_subscales",
    feedbackTemplate: "Your scores:\n- Social information processing: {scoreSp}\n- Social skills: {scoreSk}\n- Social awareness: {scoreSa}",
    items: [
      { id: "q1", text: "I can predict other peoples' behavior.", text_bn: "আমি অন্য লোকেদের আচরণের পূর্বাভাস দিতে পারি।", text_hi: "मैं अन्य लोगों के व्यवहार का पूर्वानुमान लगा सकता हूँ।", text_mr: "मी इतर लोकांच्या वर्तनाचा अंदाज लावू शकतो/शकते.", isReverse: false },
      { id: "q2", text: "I often feel that it is difficult to understand others' choices.", text_bn: "আমি প্রায়ই অনুভব করি যে অন্যদের পছন্দগুলি বোঝা কঠিন।", text_hi: "मुझे अक्सर लगता है कि दूसरों की पसंद को समझना मुश्किल है।", text_mr: "मला अनेकदा वाटते की इतरांच्या निवडी समजून घेणे कठीण आहे.", isReverse: true },
      { id: "q3", text: "I know how my actions will make others feel.", text_bn: "আমি জানি আমার কাজগুলি অন্যদের কেমন অনুভব করাবে।", text_hi: "मुझे पता होता है कि मेरे कार्यों से दूसरों को कैसा महसूस होगा।", text_mr: "माझ्या कृतींमुळे इतरांना कसे वाटेल हे मला माहित असते.", isReverse: false },
      { id: "q4", text: "I often feel uncertain around new people who I don't know.", text_bn: "আমি প্রায়ই এমন নতুন লোকেদের আশেপাশে অনিশ্চিত বোধ করি যাদের আমি চিনি না।", text_hi: "जिन्हें मैं नहीं जानता, उन नए लोगों के आसपास मैं अक्सर अनिश्चित महसूस करता हूँ।", text_mr: "मी ओळखत नसलेल्या नवीन लोकांभोवती मला अनेकदा अनिश्चित वाटते.", isReverse: true },
      { id: "q5", text: "People often surprise me with the things they do.", text_bn: "লোকেরা প্রায়ই তাদের করা জিনিসগুলি দিয়ে আমাকে অবাক করে।", text_hi: "लोग अक्सर अपने कामों से मुझे हैरान कर देते हैं।", text_mr: "लोक अनेकदा त्यांच्या कृतींनी मला आश्चर्यचकित करतात.", isReverse: true },
      { id: "q6", text: "I understand other peoples' feelings.", text_bn: "আমি অন্য লোকেদের অনুভূতি বুঝতে পারি।", text_hi: "मैं अन्य लोगों की भावनाओं को समझता हूँ।", text_mr: "मला इतर लोकांच्या भावना समजतात.", isReverse: false },
      { id: "q7", text: "I fit in easily in social situations.", text_bn: "আমি সামাজিক পরিস্থিতিতে সহজেই মানিয়ে নিতে পারি।", text_hi: "मैं सामाजिक परिस्थितियों में आसानी से घुलमिल जाता हूँ।", text_mr: "मी सामाजिक परिस्थितीत सहज मिसळतो/मिसळते.", isReverse: false },
      { id: "q8", text: "Other people become angry with me without me being able to explain why.", text_bn: "কেন তা ব্যাখ্যা করতে না পারলেও অন্য লোকেরা আমার ওপর রেগে যায়।", text_hi: "दूसरे लोग मुझ पर गुस्सा हो जाते हैं बिना इसके कि मैं समझ सकूं क्यों।", text_mr: "इतर लोक माझ्यावर रागावतात आणि मला त्याचे कारण स्पष्ट करता येत नाही.", isReverse: true },
      { id: "q9", text: "I understand others' wishes.", text_bn: "আমি অন্যদের ইচ্ছা বুঝতে পারি।", text_hi: "मैं दूसरों की इच्छाओं को समझता हूँ।", text_mr: "मला इतरांच्या इच्छा समजतात.", isReverse: false },
      { id: "q10", text: "I am good at entering new situations and meeting people for the first time.", text_bn: "আমি নতুন পরিস্থিতিতে প্রবেশ করতে এবং প্রথমবার মানুষের সাথে দেখা করতে পারদর্শী।", text_hi: "मैं नई स्थितियों में प्रवेश करने और पहली बार लोगों से मिलने में अच्छा हूँ।", text_mr: "मी नवीन परिस्थितीत प्रवेश करण्यात आणि पहिल्यांदा लोकांना भेटण्यात कुशल आहे.", isReverse: false },
      { id: "q11", text: "It seems as though people are often angry or irritated with me when I say what I think.", text_bn: "মনে হয় আমি যা ভাবি তা বললে লোকেরা প্রায়ই আমার ওপর রেগে যায় বা বিরক্ত হয়।", text_hi: "ऐसा लगता है कि जब मैं अपनी बात कहता हूँ तो लोग अक्सर मुझसे नाराज या चिढ़ जाते हैं।", text_mr: "असे वाटते की मी माझे विचार मांडतो तेव्हा लोक अनेकदा माझ्यावर रागावतात किंवा चिडतात.", isReverse: true },
      { id: "q12", text: "I have a hard time getting along with other people.", text_bn: "আমার অন্য লোকেদের সাথে মানিয়ে চলতে খুব কষ্ট হয়।", text_hi: "मुझे अन्य लोगों के साथ तालमेल बिठाने में कठिनाई होती है।", text_mr: "मला इतर लोकांशी जुळवून घेणे कठीण जाते.", isReverse: true },
      { id: "q13", text: "I find people unpredictable.", text_bn: "আমি মানুষকে অপ্রত্যাশিত মনে করি।", text_hi: "मुझे लोग अप्रत्याशित लगते हैं।", text_mr: "मला लोक अनपेक्षित वाटतात.", isReverse: true },
      { id: "q14", text: "I can often understand what others are trying to accomplish without the need for them to say anything.", text_bn: "আমি প্রায়ই বুঝতে পারি যে অন্যরা কিছু বলার প্রয়োজন ছাড়াই কী অর্জন করার চেষ্টা করছে।", text_hi: "मैं अक्सर समझ सकता हूँ कि दूसरे बिना कुछ कहे क्या हासिल करने की कोशिश कर रहे हैं।", text_mr: "इतरांना काहीही बोलण्याची गरज नसताना ते काय साध्य करण्याचा प्रयत्न करत आहेत हे मी अनेकदा समजू शकतो/शकते.", isReverse: false },
      { id: "q15", text: "It takes a long time for me to get to know others well.", text_bn: "অন্যদের ভালোভাবে চিনতে আমার অনেক সময় লাগে।", text_hi: "मुझे दूसरों को अच्छी तरह से जानने में काफी समय लगता है।", text_mr: "मला इतरांना नीट ओळखण्यासाठी बराच वेळ लागतो.", isReverse: true },
      { id: "q16", text: "I have often hurt others without realizing it.", text_bn: "আমি প্রায়ই না বুঝেই অন্যদের আঘাত করেছি।", text_hi: "मैंने अक्सर अनजाने में दूसरों को ठेस पहुंचाई है।", text_mr: "मी अनेकदा कळत नकळत इतरांना दुखावले आहे.", isReverse: true },
      { id: "q17", text: "I can predict how others will react to my behavior.", text_bn: "অন্যরা আমার আচরণে কীভাবে প্রতিক্রিয়া জানাবে আমি তার পূর্বাভাস দিতে পারি।", text_hi: "मैं अनुमान लगा सकता हूँ कि दूसरे मेरे व्यवहार पर कैसी प्रतिक्रिया देंगे।", text_mr: "माझ्या वर्तनावर इतर कशी प्रतिक्रिया देतील याचा मी अंदाज लावू शकतो/शकते.", isReverse: false },
      { id: "q18", text: "I am good at getting on good terms with new people.", text_bn: "আমি নতুন লোকেদের সাথে ভালো সম্পর্ক তৈরি করতে পারদর্শী।", text_hi: "मैं नए लोगों के साथ अच्छे संबंध बनाने में कुशल हूँ।", text_mr: "मी नवीन लोकांशी चांगले संबंध प्रस्थापित करण्यात कुशल आहे.", isReverse: false },
      { id: "q19", text: "I can often understand what others really mean through their expression, body language, etc.", text_bn: "অন্যরা তাদের অভিব্যক্তি, শারীরিক ভাষা ইত্যাদির মাধ্যমে আসলে কী বোঝাতে চায় তা আমি প্রায়ই বুঝতে পারি।", text_hi: "मैं अक्सर समझ सकता हूँ कि दूसरे अपने हाव-भाव, शारीरिक भाषा आदि से वास्तव में क्या कहना चाहते हैं।", text_mr: "इतरांना त्यांच्या चेहऱ्यावरील भाव, देहबोली इत्यादींद्वारे खरोखर काय म्हणायचे आहे हे मी अनेकदा समजू शकतो/शकते.", isReverse: false },
      { id: "q20", text: "I frequently have problems finding good conversation topics.", text_bn: "আমার কথোপকথনের ভালো বিষয় খুঁজে পেতে প্রায়ই সমস্যা হয়।", text_hi: "मुझे अक्सर बातचीत के अच्छे विषय ढूंढने में समस्या होती है।", text_mr: "मला अनेकदा संभाषणाचे चांगले विषय शोधण्यात अडचण येते.", isReverse: true },
      { id: "q21", text: "I am often surprised by others' reactions to what I do.", text_bn: "আমি যা করি তাতে অন্যদের প্রতিক্রিয়া দেখে আমি প্রায়ই অবাক হই।", text_hi: "मैं जो करता हूँ उस पर दूसरों की प्रतिक्रिया से मैं अक्सर आश्चर्यचकित होता हूँ।", text_mr: "मी जे करतो त्यावर इतरांच्या प्रतिक्रियेने मला अनेकदा आश्चर्य वाटते.", isReverse: true },
    ]
  },
  {
    id: "ncs6",
    title: "Need for Cognition (NCS-6)",
    title_bn: "জ্ঞানের প্রয়োজন (NCS-6)",
    title_hi: "सोचने-समझने की आवश्यकता (NCS-6)",
    title_mr: "विचार करण्याची गरज (NCS-6)",
    description: "For each sentence below, please select how uncharacteristic or characteristic (5-point scale) this is for you personally.",
    description_bn: "নিচের প্রতিটি বাক্যের জন্য, অনুগ্রহ করে নির্বাচন করুন এটি আপনার ব্যক্তিগতভাবে কতটা বৈশিষ্ট্যহীন বা বৈশিষ্ট্যপূর্ণ (৫-পয়েন্ট স্কেল)।",
    description_hi: "नीचे दिए गए प्रत्येक वाक्य के लिए, कृपया चुनें कि यह आपके लिए कितना अस्वाभाविक या स्वाभाविक है (5-अंक पैमाना)।",
    description_mr: "खालील प्रत्येक वाक्यासाठी, कृपया हे तुमच्यासाठी वैयक्तिकरित्या किती अस्वाभाविक किंवा स्वाभाविक आहे ते निवडा (५-पॉइंट स्केल).",
    scaleMin: 1,
    scaleMax: 5,
    scale: [
      { label: "1 (Extremely uncharacteristic)", label_bn: "১ (অত্যন্ত বৈশিষ্ট্যহীন)", label_hi: "1 (अत्यंत अस्वाभाविक)", label_mr: "१ (अत्यंत अस्वाभाविक)", value: 1 },
      { label: "2", label_bn: "২", label_hi: "2", label_mr: "२", value: 2 },
      { label: "3", label_bn: "৩", label_hi: "3", label_mr: "३", value: 3 },
      { label: "4", label_bn: "৪", label_hi: "4", label_mr: "४", value: 4 },
      { label: "5 (Extremely characteristic)", label_bn: "৫ (অত্যন্ত বৈশিষ্ট্যপূর্ণ)", label_hi: "5 (अत्यंत स्वाभाविक)", label_mr: "५ (अत्यंत स्वाभाविक)", value: 5 },
    ],
    orderType: "normal",
    scoringType: "mean",
    feedbackTemplate: "Your score on the NCS-6 is {score} points. The score can range from 1 (you do not like deep thinking) to 5 (you like effortful thinking).",
    items: [
      { id: "q1", text: "I would prefer complex to simple problems.", text_bn: "আমি সাধারণ সমস্যার চেয়ে জটিল সমস্যা পছন্দ করব।", text_hi: "मैं सरल समस्याओं की तुलना में जटिल समस्याओं को प्राथमिकता दूंगा।", text_mr: "मी साध्या समस्यांपेक्षा गुंतागुंतीच्या समस्यांना प्राधान्य देईन.", isReverse: false },
      { id: "q2", text: "I like to have the responsibility of handling a situation that requires a lot of thinking.", text_bn: "আমি এমন পরিস্থিতি মোকাবিলার দায়িত্ব নিতে পছন্দ করি যার জন্য অনেক চিন্তাভাবনার প্রয়োজন।", text_hi: "मुझे ऐसी स्थिति को संभालने की जिम्मेदारी लेना पसंद है जिसमें बहुत अधिक सोचने की आवश्यकता हो।", text_mr: "मला अशा परिस्थितीची जबाबदारी घेणे आवडते ज्यासाठी खूप विचार करावा लागतो.", isReverse: false },
      { id: "q3", text: "Thinking is not my idea of fun.", text_bn: "চিন্তা করা আমার কাছে মজার ধারণা নয়।", text_hi: "गहराई से सोचना मेरे लिए आनंद का विचार नहीं है।", text_mr: "विचार करणे ही माझ्या मते मनोरंजनाची कल्पना नाही.", isReverse: true },
      { id: "q4", text: "I would rather do something that requires little thought than something that is sure to challenge my thinking abilities.", text_bn: "আমি এমন কিছু করার চেয়ে যার জন্য সামান্য চিন্তাভাবনার প্রয়োজন হয় এমন কিছু করতে পছন্দ করব যা নিশ্চিতভাবে আমার চিন্তা করার ক্ষমতাকে চ্যালেঞ্জ করবে।", text_hi: "मैं कुछ ऐसा करने के बजाय जिसमें कम सोचने की आवश्यकता हो, ऐसा कुछ करना पसंद करूंगा जो निश्चित रूप से मेरी सोचने की क्षमता को चुनौती दे।", text_mr: "माझ्या विचार क्षमतेला नक्कीच आव्हान देणाऱ्या गोष्टीपेक्षा मी कमी विचार करावा लागेल असे काहीतरी करणे पसंत करेन.", isReverse: true },
      { id: "q5", text: "I really enjoy a task that involves coming up with new solutions to problems.", text_bn: "আমি সত্যিই এমন একটি কাজ উপভোগ করি যাতে সমস্যার নতুন সমাধান বের করতে হয়।", text_hi: "मुझे वास्तव में ऐसा कार्य पसंद है जिसमें समस्याओं के नए समाधान निकालना शामिल हो।", text_mr: "मला समस्यांवर नवीन उपाय शोधण्याचे काम मनापासून आवडते.", isReverse: false },
      { id: "q6", text: "I would prefer a task that is intellectual, difficult, and important to one that is somewhat important but does not require much thought.", text_bn: "আমি এমন একটি কাজ পছন্দ করব যা বুদ্ধিবৃত্তিক, কঠিন এবং গুরুত্বপূর্ণ, এমন কিছুর চেয়ে যা কিছুটা গুরুত্বপূর্ণ কিন্তু খুব একটা চিন্তার প্রয়োজন হয় না।", text_hi: "मैं ऐसे कार्य को प्राथमिकता दूंगा जो बौद्धिक, कठिन और महत्वपूर्ण हो, बजाय ऐसे कार्य के जो कुछ महत्वपूर्ण हो लेकिन अधिक सोच की आवश्यकता न हो।", text_mr: "मी अशा कामाला प्राधान्य देईन जे बौद्धिक, कठीण आणि महत्त्वाचे असेल, अशा कामापेक्षा जे थोडे महत्त्वाचे आहे पण जास्त विचारांची गरज नाही.", isReverse: false },
    ]
  },
  {
    id: "cfq",
    title: "Cognitive Failures (CFQ)",
    title_bn: "কগনিটিভ ফেইলিওর (CFQ)",
    title_hi: "संज्ञानात्मक त्रुटियां (CFQ)",
    title_mr: "संज्ञानात्मक त्रुटी (CFQ)",
    description: "The following questions are about minor mistakes which everyone makes from time to time, but some of which happen more often than others. We want to know how often these things have happened to you in the last six months.",
    description_bn: "নিম্নলিখিত প্রশ্নগুলি ছোটখাটো ভুল সম্পর্কে যা সবাই সময়ে সময়ে করে, তবে এর মধ্যে কয়েকটি অন্যদের চেয়ে বেশিবার ঘটে। গত ছয় মাসে আপনার সাথে কতবার এই ঘটনাগুলি ঘটেছে তা আমরা জানতে চাই।",
    description_hi: "निम्नलिखित प्रश्न छोटी-मोटी गलतियों के बारे में हैं जो हर कोई समय-समय पर करता है। हम जानना चाहते हैं कि पिछले छह महीनों में आपके साथ ये बातें कितनी बार हुई हैं।",
    description_mr: "खालील प्रश्न प्रत्येकाकडून वेळोवेळी होणाऱ्या लहान चुकांबद्दल आहेत. गेल्या सहा महिन्यांत तुमच्या बाबतीत या गोष्टी किती वेळा घडल्या आहेत हे आम्हाला जाणून घ्यायचे आहे.",
    scaleMin: 0,
    scaleMax: 4,
    scale: [
      { label: "Very often", label_bn: "খুব প্রায়ই", label_hi: "बहुत बार", label_mr: "वारंवार", value: 4 },
      { label: "Quite often", label_bn: "বেশ প্রায়ই", label_hi: "काफी बार", label_mr: "बरीच वेळा", value: 3 },
      { label: "Occasionally", label_bn: "মাঝেমধ্যে", label_hi: "कभी-कभार", label_mr: "कधीकधी", value: 2 },
      { label: "Very rarely", label_bn: "খুব কমই", label_hi: "शायद ही कभी", label_mr: "फार क्वचित", value: 1 },
      { label: "Never", label_bn: "কখনো না", label_hi: "कभी नहीं", label_mr: "कधीच नाही", value: 0 },
    ],
    orderType: "random",
    scoringType: "sum",
    feedbackTemplate: "Your score on the Cognitive Failures Questionnaire (CFQ) is {score}.",
    items: [
      { id: "q1", text: "Do you read something and find you haven't been thinking about it and must read it again?", text_bn: "আপনি কি কিছু পড়ে বুঝতে পারেন যে আপনি এটি সম্পর্কে ভাবছিলেন না এবং আপনাকে এটি আবার পড়তে হবে?", text_hi: "क्या आप कुछ पढ़ते हैं और पाते हैं कि आप इसके बारे में नहीं सोच रहे थे और आपको इसे फिर से पढ़ना होगा?", text_mr: "तुम्ही काही वाचता आणि तुमच्या लक्षात येते की तुमचे त्याकडे लक्ष नव्हते आणि तुम्हाला ते पुन्हा वाचावे लागेल?", isReverse: false },
      { id: "q2", text: "Do you find you forget why you went from one part of the house to the other?", text_bn: "আপনি কি বুঝতে পারেন যে আপনি কেন বাড়ির এক প্রান্ত থেকে অন্য প্রান্তে গিয়েছিলেন তা ভুলে গেছেন?", text_hi: "क्या आप पाते हैं कि आप भूल गए हैं कि आप घर के एक हिस्से से दूसरे हिस्से में क्यों गए थे?", text_mr: "तुम्ही घराच्या एका भागातून दुसऱ्या भागात का गेला होता हे विसरल्याचे तुमच्या लक्षात येते का?", isReverse: false },
      { id: "q3", text: "Do you fail to notice signposts on the road?", text_bn: "আপনি কি রাস্তায় দিকনির্দেশক চিহ্নগুলি লক্ষ্য করতে ব্যর্থ হন?", text_hi: "क्या आप सड़क पर लगे दिशा-सूचक चिन्हों को देखने से चूक जाते हैं?", text_mr: "रस्त्यावरील दिशादर्शक फलक पाहणे तुमच्याकडून चुकते का?", isReverse: false },
      { id: "q4", text: "Do you find you confuse right and left when giving directions?", text_bn: "দিকনির্দেশ দেওয়ার সময় আপনি কি ডান এবং বাম গুলিয়ে ফেলেন?", text_hi: "क्या दिशा-निर्देश देते समय आप दाएं और बाएं में भ्रमित हो जाते हैं?", text_mr: "दिशा दाखवताना तुमचा उजवा आणि डावा यामध्ये गोंधळ होतो का?", isReverse: false },
      { id: "q5", text: "Do you bump into people?", text_bn: "আপনি কি মানুষের সাথে ধাক্কা খান?", text_hi: "क्या आप लोगों से टकरा जाते हैं?", text_mr: "तुमची इतर लोकांशी धडक होते का?", isReverse: false },
      { id: "q6", text: "Do you find you forget whether you've turned off a light or a fire or locked the door?", text_bn: "আপনি কি আলো বা আগুন নিভিয়েছেন নাকি দরজা লক করেছেন তা ভুলে যান?", text_hi: "क्या आप यह भूल जाते हैं कि आपने लाइट बंद की या गैस बंद की या दरवाजा बंद किया?", text_mr: "तुम्ही लाइट बंद केली की नाही, किंवा गॅस बंद केला की नाही किंवा दरवाजा लॉक केला की नाही हे तुम्ही विसरता का?", isReverse: false },
      { id: "q7", text: "Do you fail to listen to people's names when you are meeting them?", text_bn: "লোকদের সাথে দেখা করার সময় আপনি কি তাদের নাম শুনতে ব্যর্থ হন?", text_hi: "क्या लोगों से मिलते समय आप उनके नाम सुनने या याद रखने में चूक जाते हैं?", text_mr: "लोकांना भेटताना तुम्ही त्यांची नावे ऐकण्यास किंवा लक्षात ठेवण्यास विसरता का?", isReverse: false },
      { id: "q8", text: "Do you say something and realize afterwards that it might be taken as insulting?", text_bn: "আপনি কি এমন কিছু বলেন যা পরে বুঝতে পারেন যে এটি অপমানজনক হিসেবে নেওয়া যেতে পারে?", text_hi: "क्या आप कुछ ऐसा कह देते हैं और बाद में महसूस करते हैं कि इसे अपमानजनक माना जा सकता है?", text_mr: "तुम्ही असे काही बोलता आणि नंतर लक्षात येते की त्याचा अपमानकारक अर्थ लावला जाऊ शकतो?", isReverse: false },
      { id: "q9", text: "Do you fail to hear people speaking to you when you are doing something else?", text_bn: "অন্য কিছু করার সময় লোকেরা আপনার সাথে কথা বললে আপনি কি শুনতে ব্যর্থ হন?", text_hi: "जब आप कुछ और कर रहे होते हैं, तो क्या आप लोगों की बात सुनने से चूक जाते हैं?", text_mr: "तुम्ही दुसरे काही करत असताना इतर लोक तुमच्याशी बोलत असल्यास तुम्ही त्यांचे ऐकण्यास चुकता का?", isReverse: false },
      { id: "q10", text: "Do you lose your temper?", text_bn: "আপনি কি আপনার মেজাজ হারান?", text_hi: "क्या आप अपना आपा खो देते हैं?", text_mr: "तुम्ही तुमचा संयम गमावता का?", isReverse: false },
    ]
  },
  {
    id: "dass21",
    title: "Depression, Anxiety, and Stress Scales (DASS-21)",
    title_bn: "হতাশা, উদ্বেগ এবং মানসিক চাপ স্কেল (DASS-21)",
    title_hi: "अवसाद, चिंता और तनाव पैमाना (DASS-21)",
    title_mr: "उदासीनता, चिंता आणि ताणतणाव प्रमाण (DASS-21)",
    description: "Please read each statement and select a number which indicates how much the statement applied to you over the past week. There are no right or wrong answers. Do not spend too much time on any statement.",
    description_bn: "অনুগ্রহ করে প্রতিটি বিবৃতি পড়ুন এবং একটি সংখ্যা নির্বাচন করুন যা নির্দেশ করে যে গত সপ্তাহে বিবৃতিটি আপনার ক্ষেত্রে কতটা প্রযোজ্য ছিল। এর কোনো সঠিক বা ভুল উত্তর নেই। কোনো বিবৃতিতে খুব বেশি সময় ব্যয় করবেন না।",
    description_hi: "कृपया प्रत्येक कथन पढ़ें और एक संख्या चुनें जो इंगित करती है कि पिछले सप्ताह में यह कथन आप पर कितना लागू हुआ। कोई सही या गलत उत्तर नहीं है।",
    description_mr: "कृपया प्रत्येक विधान वाचा आणि एक संख्या निवडा जी दर्शवते की गेल्या आठवड्यात हे विधान तुमच्यावर किती लागू झाले. कोणतीही बरोबर किंवा चूक उत्तरे नाहीत.",
    scaleMin: 0,
    scaleMax: 3,
    scale: [
      { label: "Did not apply to me at all", label_bn: "আমার ক্ষেত্রে একেবারেই প্রযোজ্য ছিল না", label_hi: "मुझ पर बिल्कुल लागू नहीं हुआ", label_mr: "माझ्यावर अजिबात लागू झाले नाही", value: 0 },
      { label: "Applied to me to some degree, or some of the time", label_bn: "কিছুটা মাত্রায় প্রযোজ্য ছিল, বা কিছু সময় প্রযোজ্য ছিল", label_hi: "कुछ हद तक, या कुछ समय के लिए लागू हुआ", label_mr: "काही प्रमाणात किंवा काही काळासाठी लागू झाले", value: 1 },
      { label: "Applied to me to a considerable degree, or a good part of time", label_bn: "যথেষ্ট মাত্রায় প্রযোজ্য ছিল, বা বেশিরভাগ সময় প্রযোজ্য ছিল", label_hi: "काफी हद तक, या अधिकांश समय के लिए लागू हुआ", label_mr: "बऱ्याच प्रमाणात किंवा बऱ्याच काळासाठी लागू झाले", value: 2 },
      { label: "Applied to me very much, or most of the time", label_bn: "আমার ক্ষেত্রে খুব বেশি প্রযোজ্য ছিল, বা প্রায় সব সময় প্রযোজ্য ছিল", label_hi: "मुझ पर बहुत अधिक, या लगभग हर समय लागू हुआ", label_mr: "माझ्यावर खूप जास्त किंवा बहुतेक वेळा लागू झाले", value: 3 },
    ],
    orderType: "normal",
    scoringType: "dass21_subscales",
    feedbackTemplate: "Your scores:\n- Depression: {scoreDepression}\n- Anxiety: {scoreAnxiety}\n- Stress: {scoreStress}",
    items: [
      { id: "q1", text: "I found it hard to wind down", text_bn: "আমার শান্ত হতে কষ্ট হচ্ছিল", text_hi: "मुझे शांत होना मुश्किल लगा", text_mr: "मला शांत होणे कठीण वाटले", isReverse: false },
      { id: "q2", text: "I was aware of dryness of my mouth", text_bn: "আমি আমার মুখ শুকিয়ে যাওয়ার বিষয়ে সচেতন ছিলাম", text_hi: "मुझे अपने मुंह के सूखेपन का अहसास था", text_mr: "माझे तोंड कोरडे पडत असल्याचे मला जाणवत होते", isReverse: false },
      { id: "q3", text: "I couldn't seem to experience any positive feeling at all", text_bn: "আমি কোনো ইতিবাচক অনুভূতি অনুভব করতে পারছিলাম না", text_hi: "मुझे बिल्कुल भी कोई सकारात्मक भावना महसूस नहीं हो रही थी", text_mr: "मला कोणतीही सकारात्मक भावना अजिबात जाणवत नव्हती", isReverse: false },
      { id: "q4", text: "I experienced breathing difficulty (e.g. excessively rapid breathing, breathlessness in the absence of physical exertion)", text_bn: "আমি শ্বাস নিতে অসুবিধা অনুভব করেছি (যেমন শারীরিক পরিশ্রম ছাড়াই খুব দ্রুত শ্বাস নেওয়া, শ্বাসকষ্ট)", text_hi: "मुझे सांस लेने में कठिनाई का अनुभव हुआ (उदा. शारीरिक मेहनत के बिना अत्यधिक तेज़ सांस लेना)", text_mr: "मला श्वास घेण्यास त्रास झाला (उदा. शारीरिक श्रमाशिवाय अतिशय जलद श्वास घेणे)", isReverse: false },
      { id: "q5", text: "I found it difficult to work up the initiative to do things", text_bn: "আমার কোনো কাজ শুরু করার উদ্যোগ নেওয়া কঠিন মনে হচ্ছিল", text_hi: "मुझे काम शुरू करने की पहल करना मुश्किल लगा", text_mr: "मला गोष्टी करण्यासाठी पुढाकार घेणे कठीण वाटले", isReverse: false },
      { id: "q6", text: "I tended to over-react to situations", text_bn: "আমি বিভিন্ন পরিস্থিতিতে অতিরিক্ত প্রতিক্রিয়া দেখানোর প্রবণতা অনুভব করেছি", text_hi: "मेरी परिस्थितियों पर अत्यधिक प्रतिक्रिया देने की प्रवृत्ति थी", text_mr: "माझी परिस्थितीवर अतिप्रतिक्रिया देण्याची प्रवृत्ती होती", isReverse: false },
      { id: "q7", text: "I experienced trembling (e.g. in the hands)", text_bn: "আমি কাঁপুনি অনুভব করেছি (যেমন হাতে)", text_hi: "मैंने कंपकंपी का अनुभव किया (उदा. हाथों में)", text_mr: "मला थरथर जाणवली (उदा. हातांमध्ये)", isReverse: false },
      { id: "q8", text: "I felt that I was using a lot of nervous energy", text_bn: "আমার মনে হচ্ছিল যে আমি প্রচুর স্নায়বিক শক্তি ব্যয় করছি", text_hi: "मुझे लगा कि मैं बहुत अधिक मानसिक ऊर्जा खर्च कर रहा हूँ", text_mr: "मला वाटले की मी खूप मज्जातंतू ऊर्जा वापरत आहे", isReverse: false },
      { id: "q9", text: "I was worried about situations in which I might panic and make a fool of myself", text_bn: "আমি এমন পরিস্থিতি নিয়ে চিন্তিত ছিলাম যেখানে আমি আতঙ্কিত হতে পারি এবং নিজেকে বোকা বানাতে পারি", text_hi: "मैं ऐसी स्थितियों के बारे में चिंतित था जिनमें मैं घबरा सकता था और खुद को मूर्ख बना सकता था", text_mr: "मी अशा परिस्थितींबद्दल काळजीत होतो/होते जिथे मला भीती वाटू शकते आणि स्वतःचे हसे होऊ शकते", isReverse: false },
      { id: "q10", text: "I felt that I had nothing to look forward to", text_bn: "আমার মনে হচ্ছিল যে আমার ভালো কিছুর আশা করার নেই", text_hi: "मुझे लगा कि मेरे पास आगे देखने के लिए कुछ भी अच्छा नहीं है", text_mr: "मला वाटले की माझ्याकडे भविष्यात आशा करण्यासारखे काही नाही", isReverse: false },
      { id: "q11", text: "I found myself getting agitated", text_bn: "আমি নিজেকে উত্তেজিত হতে দেখেছি", text_hi: "मैंने खुद को उत्तेजित/बेचैन पाया", text_mr: "मला स्वतःमध्ये अस्वस्थता जाणवली", isReverse: false },
      { id: "q12", text: "I found it difficult to relax", text_bn: "আমার আরাম করতে অসুবিধা হচ্ছিল", text_hi: "मुझे आराम करना मुश्किल लगा", text_mr: "मला आराम करणे कठीण वाटले", isReverse: false },
      { id: "q13", text: "I felt down-hearted and blue", text_bn: "আমি হতাশ এবং বিষণ্ণ অনুভব করেছি", text_hi: "मैंने उदास और निराश महसूस किया", text_mr: "मला अत्यंत खिन्न आणि उदास वाटले", isReverse: false },
      { id: "q14", text: "I was intolerant of anything that kept me from getting on with what I was doing", text_bn: "আমি এমন কিছুর প্রতি অসহিষ্ণু ছিলাম যা আমাকে আমার কাজ করতে বাধা দেয়", text_hi: "मैं ऐसी किसी भी चीज़ के प्रति असहिष्णु था जो मुझे मेरा काम करने से रोकती थी", text_mr: "मी जे करत होतो ते चालू ठेवण्यापासून रोखणाऱ्या कशाचाही मला राग येत होता", isReverse: false },
      { id: "q15", text: "I felt I was close to panic", text_bn: "আমি অনুভব করেছি যে আমি আতঙ্কের কাছাকাছি ছিলাম", text_hi: "मुझे लगा कि मैं घबराहट (पैनिक) के करीब था", text_mr: "मला वाटले की मी अत्यंत भीती किंवा घबराटीच्या जवळ पोहोचलो होतो", isReverse: false },
      { id: "q16", text: "I was unable to become enthusiastic about anything", text_bn: "আমি কোনো কিছু নিয়ে উৎসাহী হতে পারছিলাম না", text_hi: "मैं किसी भी बात को लेकर उत्साहित नहीं हो पा रहा था", text_mr: "मी कशाबद्दलही उत्साही होऊ शकत नव्हतो", isReverse: false },
      { id: "q17", text: "I felt I wasn't worth much as a person", text_bn: "আমার মনে হচ্ছিল একজন ব্যক্তি হিসেবে আমার কোনো মূল্য নেই", text_hi: "मुझे लगा कि एक व्यक्ति के रूप में मेरा कोई मूल्य नहीं है", text_mr: "मला वाटले की एक व्यक्ती म्हणून माझे काही मूल्य नाही", isReverse: false },
      { id: "q18", text: "I felt that I was rather touchy", text_bn: "আমার মনে হচ্ছিল যে আমি বেশ স্পর্শকাতর (সহজেই রেগে যাওয়া)", text_hi: "मुझे लगा कि मैं बहुत चिड़चिड़ा हो रहा था", text_mr: "मला वाटले की मी खूप संवेदनशील/चिडखोर झालो होतो", isReverse: false },
      { id: "q19", text: "I was aware of the action of my heart in the absence of physical exertion (e.g. sense of heart rate increase, heart missing a beat)", text_bn: "শারীরিক পরিশ্রমের অনুপস্থিতিতেও আমি আমার হৃদস্পন্দনের ক্রিয়া সম্পর্কে সচেতন ছিলাম (যেমন হৃদস্পন্দন বৃদ্ধির অনুভূতি, হৃদস্পন্দন বাদ পড়া)", text_hi: "शारीरिक परिश्रम के बिना भी मुझे अपने दिल की धड़कन का अहसास हो रहा था (उदा. दिल की धड़कन तेज होना)", text_mr: "शारीरिक हालचालींशिवाय मला माझ्या हृदयाच्या ठोक्यांची जाणीव होत होती (उदा. हृदयाचे ठोके वाढणे)", isReverse: false },
      { id: "q20", text: "I felt scared without any good reason", text_bn: "আমি কোনো যুক্তিসঙ্গত কারণ ছাড়াই ভয় পেয়েছি", text_hi: "मुझे बिना किसी ठोस कारण के डर लग रहा था", text_mr: "मला कोणत्याही योग्य कारणाशिवाय भीती वाटली", isReverse: false },
      { id: "q21", text: "I felt that life was meaningless", text_bn: "আমার মনে হচ্ছিল জীবনটা অর্থহীন", text_hi: "मुझे लगा कि जीवन अर्थहीन है", text_mr: "मला वाटले की आयुष्य निरर्थक आहे", isReverse: false }
    ]
  },
  {
    id: "phq9",
    title: "Patient Health Questionnaire (PHQ-9)",
    title_bn: "রোগীর স্বাস্থ্য প্রশ্নাবলী (PHQ-9)",
    title_hi: "रोगी स्वास्थ्य प्रश्नावली (PHQ-9)",
    title_mr: "रुग्ण आरोग्य प्रश्नावली (PHQ-9)",
    description: "Over the last 2 weeks, how often have you been bothered by any of the following problems?",
    description_bn: "গত ২ সপ্তাহে, আপনি নিচের কোনো সমস্যা দ্বারা কতবার বিরক্ত হয়েছেন?",
    description_hi: "पिछले 2 हफ्तों में, आप निम्नलिखित में से किसी भी समस्या से कितनी बार परेशान हुए हैं?",
    description_mr: "गेल्या २ आठवड्यांत, तुम्हाला खालीलपैकी कोणत्या समस्यांचा किती वेळा त्रास झाला आहे?",
    scaleMin: 0,
    scaleMax: 3,
    scale: [
      { label: "Not at all", label_bn: "কখনো না", label_hi: "बिल्कुल नहीं", label_mr: "अजिबात नाही", value: 0 },
      { label: "Several days", label_bn: "কয়েক দিন", label_hi: "कई दिन", label_mr: "काही दिवस", value: 1 },
      { label: "More than half the days", label_bn: "অর্ধেকের বেশি দিন", label_hi: "आधे से अधिक दिन", label_mr: "निम्म्याहून अधिक दिवस", value: 2 },
      { label: "Nearly every day", label_bn: "প্রায় প্রতিদিন", label_hi: "लगभग हर दिन", label_mr: "जवळजवळ दररोज", value: 3 },
    ],
    orderType: "normal",
    scoringType: "sum",
    feedbackTemplate: "Your PHQ-9 score is {score}.",
    items: [
      { id: "q1", text: "Little interest or pleasure in doing things", text_bn: "কাজ করার প্রতি খুব কম আগ্রহ বা আনন্দ", text_hi: "चीजें करने में बहुत कम रुचि या आनंद", text_mr: "गोष्टी करण्यात कमी रस किंवा आनंद वाटणे", isReverse: false },
      { id: "q2", text: "Feeling down, depressed, or hopeless", text_bn: "বিষণ্ণ, মন খারাপ বা আশাহীন বোধ করা", text_hi: "उदास, निराश या मायूस महसूस करना", text_mr: "उदास, खिन्न किंवा निराश वाटणे", isReverse: false },
      { id: "q3", text: "Trouble falling or staying asleep, or sleeping too much", text_bn: "ঘুমাতে বা ঘুমিয়ে থাকতে সমস্যা, অথবা খুব বেশি ঘুমানো", text_hi: "सोने में परेशानी या बहुत अधिक सोना", text_mr: "झोप लागण्यास किंवा झोप टिकून राहण्यास त्रास, किंवा खूप जास्त झोपणे", isReverse: false },
      { id: "q4", text: "Feeling tired or having little energy", text_bn: "ক্লান্ত বোধ করা বা খুব কম শক্তি থাকা", text_hi: "थकान महसूस होना या ऊर्जा की कमी होना", text_mr: "थकवा जाणवणे किंवा ऊर्जा कमी असणे", isReverse: false },
      { id: "q5", text: "Poor appetite or overeating", text_bn: "ক্ষুধা মন্দা বা অতিরিক্ত খাওয়া", text_hi: "भूख न लगना या अत्यधिक खाना", text_mr: "कमी भूक लागणे किंवा अति खाणे", isReverse: false },
      { id: "q6", text: "Feeling bad about yourself - or that you are a failure or have let yourself or your family down", text_bn: "নিজের সম্পর্কে খারাপ বোধ করা - অথবা আপনি একজন ব্যর্থ মানুষ বা আপনি নিজেকে বা আপনার পরিবারকে হতাশ করেছেন", text_hi: "अपने बारे में बुरा महसूस करना - या कि आप असफल हैं या आपने खुद को या अपने परिवार को निराश किया है", text_mr: "स्वतःबद्दल वाईट वाटणे - किंवा आपण अयशस्वी आहात किंवा आपण स्वतःला किंवा कुटुंबाला निराश केले आहे असे वाटणे", isReverse: false },
      { id: "q7", text: "Trouble concentrating on things, such as reading the newspaper or watching television", text_bn: "খবরের কাগজ পড়া বা টেলিভিশন দেখার মতো বিষয়গুলিতে মনোযোগ দিতে সমস্যা", text_hi: "अखबार पढ़ने या टेलीविजन देखने जैसी चीजों पर ध्यान केंद्रित करने में परेशानी", text_mr: "वर्तमानपत्र वाचणे किंवा टीव्ही पाहणे यासारख्या गोष्टींवर लक्ष केंद्रित करण्यात अडचण येणे", isReverse: false },
      { id: "q8", text: "Moving or speaking so slowly that other people could have noticed. Or the opposite - being so fidgety or restless that you have been moving around a lot more than usual", text_bn: "এত ধীরে ধীরে নড়াচড়া করা বা কথা বলা যে অন্য লোকেরা তা লক্ষ্য করতে পারে। অথবা এর বিপরীত - এতটাই অস্থির বা চঞ্চল হওয়া যে আপনি স্বাভাবিকের চেয়ে অনেক বেশি ঘোরাঘুরি করছেন", text_hi: "इतनी धीमी गति से चलना या बोलना कि अन्य लोग इसे नोटिस कर सकें। या इसके विपरीत - इतना बेचैन होना कि आप सामान्य से बहुत अधिक घूम रहे हों", text_mr: "इतक्या हळू हालचाल करणे किंवा बोलणे की इतर लोकांच्या लक्षात आले असावे. किंवा उलट - इतके अस्वस्थ असणे की नेहमीपेक्षा जास्त हालचाल करणे", isReverse: false },
      { id: "q9", text: "Thoughts that you would be better off dead, or of hurting yourself", text_bn: "এমন চিন্তাভাবনা যে আপনি মারা গেলেই ভালো হতো, বা নিজের ক্ষতি করার চিন্তা", text_hi: "ऐसे विचार कि आप मर जाएं तो बेहतर होगा, या खुद को चोट पहुँचाने के विचार", text_mr: "आपण मेलो तर बरे होईल असे विचार येणे किंवा स्वतःला इजा करून घेण्याचे विचार येणे", isReverse: false }
    ]
  },
  {
    id: "gad7",
    title: "Generalized Anxiety Disorder Scale (GAD-7)",
    title_bn: "সাধারণ উদ্বেগ ব্যাধি স্কেল (GAD-7)",
    title_hi: "सामान्यीकृत चिंता विकार पैमाना (GAD-7)",
    title_mr: "सामान्यीकृत चिंता विकार प्रमाण (GAD-7)",
    description: "Over the last 2 weeks, how often have you been bothered by the following problems?",
    description_bn: "গত ২ সপ্তাহে, আপনি নিচের সমস্যাগুলি দ্বারা কতবার বিরক্ত হয়েছেন?",
    description_hi: "पिछले 2 हफ्तों में, आप निम्नलिखित समस्याओं से कितनी बार परेशान हुए हैं?",
    description_mr: "गेल्या २ आठवड्यांत, तुम्हाला खालील समस्यांचा किती वेळा त्रास झाला आहे?",
    scaleMin: 0,
    scaleMax: 3,
    scale: [
      { label: "Not at all", label_bn: "কখনো না", label_hi: "बिल्कुल नहीं", label_mr: "अजिबात नाही", value: 0 },
      { label: "Several days", label_bn: "কয়েক দিন", label_hi: "कई दिन", label_mr: "काही दिवस", value: 1 },
      { label: "More than half the days", label_bn: "অর্ধেকের বেশি দিন", label_hi: "आधे से अधिक दिन", label_mr: "निम्म्याहून अधिक दिवस", value: 2 },
      { label: "Nearly every day", label_bn: "প্রায় প্রতিদিন", label_hi: "लगभग हर दिन", label_mr: "जवळजवळ दररोज", value: 3 },
    ],
    orderType: "normal",
    scoringType: "sum",
    feedbackTemplate: "Your GAD-7 score is {score}.",
    items: [
      { id: "q1", text: "Feeling nervous, anxious, or on edge", text_bn: "স্নায়বিক চাপ, উদ্বেগ, বা প্রান্তে (edge) অনুভব করা", text_hi: "घबराहट, चिंता या बेचैनी महसूस करना", text_mr: "घाबरल्यासारखे, चिंताग्रस्त किंवा अस्वस्थ वाटणे", isReverse: false },
      { id: "q2", text: "Not being able to stop or control worrying", text_bn: "চিন্তা করা থামাতে বা নিয়ন্ত্রণ করতে না পারা", text_hi: "चिंता करना बंद करने या नियंत्रित करने में असमर्थ होना", text_mr: "काळजी करणे थांबवणे किंवा नियंत्रित करणे शक्य न होणे", isReverse: false },
      { id: "q3", text: "Worrying too much about different things", text_bn: "বিভিন্ন জিনিস নিয়ে খুব বেশি চিন্তা করা", text_hi: "अलग-अलग चीजों के बारे में बहुत अधिक चिंता करना", text_mr: "वेगवेगळ्या गोष्टींबद्दल खूप जास्त काळजी वाटणे", isReverse: false },
      { id: "q4", text: "Trouble relaxing", text_bn: "আরাম করতে সমস্যা", text_hi: "आराम करने में परेशानी होना", text_mr: "शांत बसणे किंवा रिलॅक्स होणे कठीण जाणे", isReverse: false },
      { id: "q5", text: "Being so restless that it is hard to sit still", text_bn: "এত অস্থির হওয়া যে স্থির হয়ে বসে থাকা কঠিন", text_hi: "इतना बेचैन होना कि स्थिर बैठना मुश्किल हो", text_mr: "इतके अस्वस्थ असणे की शांत बसणे कठीण जाणे", isReverse: false },
      { id: "q6", text: "Becoming easily annoyed or irritable", text_bn: "সহজেই বিরক্ত বা রাগান্বিত হওয়া", text_hi: "आसानी से नाराज या चिड़चिड़ा होना", text_mr: "सहज चिडणे किंवा रागावणे", isReverse: false },
      { id: "q7", text: "Feeling afraid, as if something awful might happen", text_bn: "ভয় পাওয়া, যেন ভয়ঙ্কর কিছু ঘটতে পারে", text_hi: "डर लगना, जैसे कुछ भयानक होने वाला हो", text_mr: "काहीतरी भयंकर घडेल अशी भीती वाटणे", isReverse: false }
    ]
  },
  {
    id: "who5",
    title: "WHO-5 Well-Being Index",
    title_bn: "WHO-5 সুস্থতা সূচক",
    title_hi: "WHO-5 कल्याण सूचकांक",
    title_mr: "WHO-5 स्वास्थ्य निर्देशांक",
    description: "Please indicate for each of the five statements which is closest to how you have been feeling over the last two weeks.",
    description_bn: "গত দুই সপ্তাহে আপনি কেমন বোধ করছেন তার সবচেয়ে কাছাকাছি পাঁচটি বিবৃতির প্রত্যেকটির জন্য অনুগ্রহ করে নির্দেশ করুন।",
    description_hi: "कृपया पिछले दो हफ्तों के दौरान आप कैसा महसूस कर रहे हैं, इसके सबसे करीब विकल्प चुनें।",
    description_mr: "गेल्या दोन आठवड्यांत तुम्हाला कसे वाटत आहे याच्याशी सर्वात जवळचे विधान निवडा.",
    scaleMin: 0,
    scaleMax: 5,
    scale: [
      { label: "At no time", label_bn: "কখনো না", label_hi: "कभी नहीं", label_mr: "कधीच नाही", value: 0 },
      { label: "Some of the time", label_bn: "কিছু সময়", label_hi: "कुछ समय", label_mr: "काही वेळ", value: 1 },
      { label: "Less than half of the time", label_bn: "অর্ধেকের কম সময়", label_hi: "आधे से कम समय", label_mr: "निम्म्यापेक्षा कमी वेळ", value: 2 },
      { label: "More than half of the time", label_bn: "অর্ধেকের বেশি সময়", label_hi: "आधे से अधिक समय", label_mr: "निम्म्यापेक्षा जास्त वेळ", value: 3 },
      { label: "Most of the time", label_bn: "বেশিরভাগ সময়", label_hi: "अधिकांश समय", label_mr: "बहुतेक वेळ", value: 4 },
      { label: "All of the time", label_bn: "সব সময়", label_hi: "हर समय", label_mr: "सर्व वेळ", value: 5 },
    ],
    orderType: "normal",
    scoringType: "sum",
    feedbackTemplate: "Your WHO-5 raw score is {score}. (Multiply by 4 to get a percentage 0-100).",
    items: [
      { id: "q1", text: "I have felt cheerful and in good spirits", text_bn: "আমি প্রফুল্ল এবং ভালো মেজাজে অনুভব করেছি", text_hi: "मैं प्रफुल्लित और अच्छे मिजाज में महसूस कर रहा हूँ", text_mr: "मला आनंदी आणि उत्साही वाटले आहे", isReverse: false },
      { id: "q2", text: "I have felt calm and relaxed", text_bn: "আমি শান্ত এবং শিথিল অনুভব করেছি", text_hi: "मैं शांत और तनावमुक्त महसूस कर रहा हूँ", text_mr: "मला शांत आणि तणावमुक्त वाटले आहे", isReverse: false },
      { id: "q3", text: "I have felt active and vigorous", text_bn: "আমি সক্রিয় এবং উদ্যমী অনুভব করেছি", text_hi: "मैं सक्रिय और ऊर्जावान महसूस कर रहा हूँ", text_mr: "मला सक्रिय आणि उत्साही वाटले आहे", isReverse: false },
      { id: "q4", text: "I woke up feeling fresh and rested", text_bn: "আমি সতেজ এবং বিশ্রাম নিয়ে জেগে উঠেছি", text_hi: "मैं तरोताजा और आराम महसूस करते हुए उठा", text_mr: "मी ताजेतवाने आणि विश्रांती घेऊन उठलो/उठले", isReverse: false },
      { id: "q5", text: "My daily life has been filled with things that interest me", text_bn: "আমার দৈনন্দিন জীবন আমার আগ্রহের বিষয় দিয়ে পূর্ণ ছিল", text_hi: "मेरा दैनिक जीवन मेरी रुचि की चीजों से भरा हुआ है", text_mr: "माझे दैनंदिन जीवन माझ्या आवडीच्या गोष्टींनी भरलेले आहे", isReverse: false }
    ]
  }
];
